In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [6]:
df = pd.read_csv('../../dataset/features.csv')

In [7]:
import ast

feature_cols = [
    'mfcc_mean',
    'mfcc_delta_mean',
    'mfcc_delta2_mean',
    'mel_spec_db_mean',
]

for col in feature_cols:
    df[col] = df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    df[col] = df[col].apply(lambda x: sum(x) / len(x) if isinstance(x, list) else x)


In [8]:
df

Gender  Age Emotion Emotion levels  \
0       Male   42     ANG             XX   
1       Male   29     HAP             XX   
2     Female   52     ANG             MD   
3       Male   62     HAP             LO   
4     Female   33     ANG             XX   
...      ...  ...     ...            ...   
7437  Female   20     FEA             XX   
7438  Female   21     NEU             XX   
7439    Male   45     ANG             LO   
7440    Male   32     NEU             XX   
7441    Male   22     DIS             XX   

                                        Location  mfcc_mean  mfcc_delta_mean  \
0     ../../dataset/AudioWAV/1041_IOM_ANG_XX.wav  -9.889783        -0.026791   
1     ../../dataset/AudioWAV/1005_ITH_HAP_XX.wav -14.319490        -0.008121   
2     ../../dataset/AudioWAV/1056_IEO_ANG_MD.wav -10.598191         0.000172   
3     ../../dataset/AudioWAV/1087_IEO_HAP_LO.wav -13.321998        -0.011745   
4     ../../dataset/AudioWAV/1052_MTI_ANG_XX.wav -10.971943         0.006647   
...                                          ...        ...              ...   
7437  ../../dataset/AudioWAV/1082_TAI_FEA_XX.wav -12.769634         0.024217   
7438  ../../dataset/AudioWAV/1002_MTI_NEU_XX.wav -16.304217        -0.002686   
7439  ../../dataset/AudioWAV/1083_IEO_ANG_LO.wav -10.881321         0.005241   
7440  ../../dataset/AudioWAV/1011_IOM_NEU_XX.wav -11.946458         0.008935   
7441  ../../dataset/AudioWAV/1045_ITH_DIS_XX.wav -12.623084         0.002829   

      mfcc_delta2_mean  mel_spec_db_mean  spectral_centroid_mean  zcr_mean  
0            -0.032141        -56.827071             1179.349322  0.043249  
1             0.001389        -53.707450             1500.493431  0.070299  
2            -0.007669        -61.971771             1761.658971  0.085656  
3            -0.008918        -54.003731             1117.330547  0.036856  
4            -0.005334        -57.965145             1439.093152  0.064631  
...                ...               ...                     ...       ...  
7437          0.023551        -53.149645             1733.797389  0.094620  
7438         -0.000699        -51.632801             1312.391145  0.051037  
7439          0.017308        -52.594525             1825.146631  0.092624  
7440         -0.004965        -51.789469             1140.460215  0.037141  
7441         -0.004006        -46.701443             1215.057451  0.043496  

[7442 rows x 11 columns]

In [9]:
feature_cols = [
    'mfcc_mean',
    'mfcc_delta_mean',
    'mfcc_delta2_mean',
    'mel_spec_db_mean',
    'spectral_centroid_mean',
    'zcr_mean'
]
X = df[feature_cols]
y = df['Emotion']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [11]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
n_neighbors = np.arange(1,51)
parameters = {'n_neighbors':n_neighbors, 'metric':('hamming', 'euclidean', 'manhattan')}
classifier = KNeighborsClassifier()
clf = GridSearchCV(classifier, parameters, scoring='accuracy', cv=5, verbose=3)
clf.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits
[CV 1/5] END .....metric=hamming, n_neighbors=1;, score=0.170 total time=   0.2s
[CV 2/5] END .....metric=hamming, n_neighbors=1;, score=0.150 total time=   0.2s
[CV 3/5] END .....metric=hamming, n_neighbors=1;, score=0.173 total time=   0.2s
[CV 4/5] END .....metric=hamming, n_neighbors=1;, score=0.171 total time=   0.1s
[CV 5/5] END .....metric=hamming, n_neighbors=1;, score=0.149 total time=   0.1s
[CV 1/5] END .....metric=hamming, n_neighbors=2;, score=0.170 total time=   0.1s
[CV 2/5] END .....metric=hamming, n_neighbors=2;, score=0.151 total time=   0.1s
[CV 3/5] END .....metric=hamming, n_neighbors=2;, score=0.171 total time=   0.1s
[CV 4/5] END .....metric=hamming, n_neighbors=2;, score=0.171 total time=   0.1s
[CV 5/5] END .....metric=hamming, n_neighbors=2;, score=0.149 total time=   0.2s
[CV 1/5] END .....metric=hamming, n_neighbors=3;, score=0.172 total time=   0.2s
[CV 2/5] END .....metric=hamming, n_neighbors=

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ('hamming', 'euclidean', 'manhattan'),
                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])},
             scoring='accuracy', verbose=3)

In [13]:
print("best score: ", clf.best_score_)
print("best hyperparameters: ", clf.best_params_)

best score:  0.3525930472944846
best hyperparameters:  {'metric': 'manhattan', 'n_neighbors': np.int64(42)}


In [14]:
knn = KNeighborsClassifier(n_neighbors=42, metric='manhattan')
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=42)

In [15]:
y_pred = knn.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[183  19  14  28   9   1]
 [ 47  58  26  33  33  57]
 [ 63  33  29  33  45  51]
 [ 70  37  28  62  32  26]
 [ 14  36  22  35  63  48]
 [  5  34  22  12  40 141]]
              precision    recall  f1-score   support

         ANG       0.48      0.72      0.58       254
         DIS       0.27      0.23      0.25       254
         FEA       0.21      0.11      0.15       254
         HAP       0.31      0.24      0.27       255
         NEU       0.28      0.29      0.29       218
         SAD       0.44      0.56      0.49       254

    accuracy                           0.36      1489
   macro avg       0.33      0.36      0.34      1489
weighted avg       0.33      0.36      0.34      1489



In [18]:
n_components = df['Emotion'].nunique() - 1
lda = LinearDiscriminantAnalysis(n_components=n_components)
X_train_lda = lda.fit_transform(X_train_scaled, y_train)
X_test_lda = lda.transform(X_test_scaled)

In [20]:
print(f'Original number of features: {X_train.shape[1]}')
print(f'Number of features after LDA: {X_train_lda.shape[1]}')

Original number of features: 6
Number of features after LDA: 5


In [21]:
n_neighbors = np.arange(1,51)
parameters = {'n_neighbors':n_neighbors, 'metric':('hamming', 'euclidean', 'manhattan')}
classifier = KNeighborsClassifier()
clf = GridSearchCV(classifier, parameters, scoring='accuracy', cv=5, verbose=3)
clf.fit(X_train_lda, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits
[CV 1/5] END .....metric=hamming, n_neighbors=1;, score=0.171 total time=   0.2s
[CV 2/5] END .....metric=hamming, n_neighbors=1;, score=0.170 total time=   0.2s
[CV 3/5] END .....metric=hamming, n_neighbors=1;, score=0.146 total time=   0.2s
[CV 4/5] END .....metric=hamming, n_neighbors=1;, score=0.171 total time=   0.1s
[CV 5/5] END .....metric=hamming, n_neighbors=1;, score=0.171 total time=   0.1s
[CV 1/5] END .....metric=hamming, n_neighbors=2;, score=0.171 total time=   0.1s
[CV 2/5] END .....metric=hamming, n_neighbors=2;, score=0.170 total time=   0.1s
[CV 3/5] END .....metric=hamming, n_neighbors=2;, score=0.170 total time=   0.1s
[CV 4/5] END .....metric=hamming, n_neighbors=2;, score=0.171 total time=   0.2s
[CV 5/5] END .....metric=hamming, n_neighbors=2;, score=0.171 total time=   0.2s
[CV 1/5] END .....metric=hamming, n_neighbors=3;, score=0.171 total time=   0.2s
[CV 2/5] END .....metric=hamming, n_neighbors=

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ('hamming', 'euclidean', 'manhattan'),
                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])},
             scoring='accuracy', verbose=3)

In [22]:
print("best score: ", clf.best_score_)
print("best hyperparameters: ", clf.best_params_)

best score:  0.3609917518644738
best hyperparameters:  {'metric': 'manhattan', 'n_neighbors': np.int64(49)}


In [23]:
knn = KNeighborsClassifier(n_neighbors=49, metric='manhattan')
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=49)

In [24]:
y_pred = knn.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[181  20   9  34   9   1]
 [ 46  53  25  37  33  60]
 [ 63  33  27  31  46  54]
 [ 67  42  26  58  37  25]
 [ 11  38  25  35  64  45]
 [  8  31  17  12  41 145]]
              precision    recall  f1-score   support

         ANG       0.48      0.71      0.57       254
         DIS       0.24      0.21      0.23       254
         FEA       0.21      0.11      0.14       254
         HAP       0.28      0.23      0.25       255
         NEU       0.28      0.29      0.29       218
         SAD       0.44      0.57      0.50       254

    accuracy                           0.35      1489
   macro avg       0.32      0.35      0.33      1489
weighted avg       0.32      0.35      0.33      1489

